### ISSUE TITLE
Implement better CSS and Grid methodologies

### ISSUE THREAD

**Issue by bentok** [bentok/fantasy-beer-league#14]
The current grid system is crappy, it would be nice to switch to CSS Grid. We need to decide on an overall CSS methodology as well.

**Comment by rabidpaul** [comment]
I'd say my thoughts have evolved lately on methodologies in component-based style systems. I'd like to have some general global framework stuff for a project using BEM and a consistent set of utilities and mixins. But the components themselves should just be as minimal as possible style-wise. No need for BEM, and element styles are fine as long as you're not undoing and redoing styles all the time. And `/deep/` should never be used.

What do you think about a global styles folder using ITCSS layers? Normalize for reset? Autoprefixer?

**Comment by bentok** [comment]
I am all for ITCSS, normalize and autoprefixer.

**Comment by rabidpaul** [comment]
Great. I'll jump in and put those three in, along with some helper classes for flexbox, and some responsive spacing utils.
