### ISSUE TITLE
User Profile Page

### ISSUE THREAD

**Issue by bentok** [bentok/fantasy-beer-league#9]
Create a user profile page which allows the user to edit their information.

- Their primary email should be displayed in a field but disabled.
- Follow the fields described in #3.
- If any additional fields are needed, update the schema outlined in #3 via comments.
- Page should be a reactive form
- Should use validators to ensure the correct input types are used
- Hit the user endpoint with a PUT method upon submission

**Comment by rabidpaul** [comment]
I'll take this one if you want to assign it. I guess I don't have permissions as a collab to assign it to myself.

**Comment by bentok** [comment]
Np, I just added you as a collaborator.
